### ISSUE TITLE
label_keep seems to be victoriametrics specifically

### ISSUE THREAD

**Issue by halkeye** [blesswinsamuel/grafana-dashboards#1]
https://docs.victoriametrics.com/metricsql/#label_keep

https://github.com/blesswinsamuel/grafana-dashboards/blob/f72e55aa53242d4470ac65777dbfed318dd3188e/dashboards/smartctl.ts#L61-L71

I'm not sure if you want to make it more portable with something else

I removed them from my queries with no ill effect, so not sure if its something about Victoria

![image](https://github.com/blesswinsamuel/grafana-dashboards/assets/110087/e819e3fa-d2e6-4b59-8d88-911fea77f599)

**Comment by blesswinsamuel** [comment]
Hi @halkeye, thanks for opening this issue :). The reason for using label_keep was to see less noise in the transform tab of this panel in the grafana dashboard. Without `label_keep`, it looks like this:

<img width="1914" alt="image" src="https://github.com/blesswinsamuel/grafana-dashboards/assets/815723/2ffd120b-6883-4cc9-8bbf-1e635a58cff1">

And with label_keep:

<img width="1923" alt="image" src="https://github.com/blesswinsamuel/grafana-dashboards/assets/815723/23e418fb-16e9-479e-a986-68c2cd56d546">

So I changed it to `sum` aggregation, which should work with prometheus as well.

**Comment by halkeye** [comment]
Awesome. I kinda figured you'd say no because you wanted it for your own stuff, so i'm happy you are fixing it!
