### ISSUE TITLE
[smartctl] Incorrect temperature aggregation

### ISSUE THREAD

**Issue by maxpain** [blesswinsamuel/grafana-dashboards#2]
Hello. I have many of these disks, and the temperatures are summed up.

<img width="806" alt="image" src="https://github.com/user-attachments/assets/7ebfec10-c876-41f9-9004-389fbd4c1a0c">

**Comment by blesswinsamuel** [comment]
Hi @maxpain, thanks for raising this. It looks like you have multiple disks with same disk model name (please correct me if my guess is wrong). I've pushed https://github.com/blesswinsamuel/grafana-dashboards/commit/1c8f326a46b670172a9fbaae10bc7d70e410bcbc which might fix this. Please reopen if it doesn't fix it.
