### ISSUE TITLE
[smartctl] Group by model_name + serial_number

### ISSUE THREAD

**Issue by maxpain** [blesswinsamuel/grafana-dashboards#3]
Hello. Currently, if you have a lot of disks with the same model, each chart shows summed values by `model_name`.
I think we need to group by `model_name` + `serial_number`

**Comment by blesswinsamuel** [comment]
I believe this is addressed by the fix for https://github.com/blesswinsamuel/grafana-dashboards/issues/2. Please feel free to reopen if not.
